### ISSUE TITLE
No add button after hitting 'show more'

### ISSUE THREAD

**Issue by cococow123** [Circularify/Queue-n-Play#7] opened 2017-03-19 00:20 UTC
Hello again!

When I am looking through the recommended videos on the side, and I hit the 'show more' button. There are no more add buttons for the queue.

It would be great if you could fix this small bug!

Thanks!

**Comment by martijnlentink** [comment] 2017-03-19 08:04
Hi there Coco! 

Thank you for reporting this issue. Since this is a duplicate of [this issue](https://github.com/Circularify/Queue-n-Play/issues/4), we already had the chance to fix the problem. The fix will be integrated in next release.

Martijn

**Comment by dickwolff** [comment] 2017-03-20 10:54
Closing, marked as duplicate as stated by @martijnlentink (#4)

**Closed as completed by dickwolff** 2017-03-20 10:54 UTC
Labels: Duplicate
